---- This file must run after the database and all tables have been created.
---- This seed script was generated by ChatGPT, with minor tweaks by the team to fix issues.
---- START OF CHATGPT SEED SCRIPT
DELETE FROM UserAvailability;
DELETE FROM SquadMembers;
DELETE FROM Users;
DELETE FROM Squads;


---- Generated Users - PwHash is a hashed version of 'Password'
INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'John', 'Smith', 'johnsmith@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Emily', 'Johnson', 'emilyjohnson@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Michael', 'Williams', 'michaelwilliams@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Sophia', 'Brown', 'sophiabrown@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Mohammed', 'Ali', 'mohammedali@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Anna', 'Martinez', 'annamartinez@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Liam', 'Garcia', 'liamgarcia@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Emma', 'Rodriguez', 'emmarodriguez@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Ethan', 'Lopez', 'ethanlopez@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Olivia', 'Lee', 'olivialee@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Muhammad', 'Wang', 'muhammadwang@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Ava', 'Kim', 'avakim@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Noah', 'Singh', 'noahsingh@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Isabella', 'Hernandez', 'isabellahernandez@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'William', 'Nguyen', 'williamnguyen@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Sofia', 'Takahashi', 'sofiatakahashi@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'James', 'Müller', 'jamesmuller@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Mia', 'Sato', 'miasato@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Benjamin', 'Chen', 'benjaminchen@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Charlotte', 'Kumar', 'charlottekumar@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Daniel', 'Gupta', 'danielgupta@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Amelia', 'Patel', 'ameliapatel@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Logan', 'Tan', 'logantan@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Evelyn', 'Wong', 'evelynwong@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Alexander', 'Kim', 'alexanderkim@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 0);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Yuna', 'Ito', 'yunaito@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 1);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Jacob', 'Wu', 'jacobwu@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 1);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Harper', 'Lee', 'harperlee@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 1);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Aiden', 'Choi', 'aidenchoi@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 1);

INSERT INTO USERS (UserPk, FirstName, LastName, Email, PwHash, PwSalt, IsDeleted) 
VALUES (NEWID(), 'Emma', 'Ivanov', 'emmaivanov@bademail.com', 'WklCAUD9+zUZsCBoTDtzJPhfRtxWzNBZ5fC14zV6vd8=', 'xXhK/PNFxya0Bh+Vd1HOoA==', 1);

---- Generated Squads
INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Mighty Morphin Mangoes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id nisi vel risus tincidunt dictum. Mauris eu nulla ut ligula rhoncus convallis. Vestibulum scelerisque, elit vel tempor ultrices, metus felis pulvinar orci, in varius eros justo ac nulla. Nulla facilisi. In tempor, ante et interdum rutrum, magna mi tincidunt odio, ac condimentum tortor ante id quam. ', 'New York, NY', 0);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Dazzling Disco Ducks', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam laoreet, risus et tincidunt placerat, nulla purus suscipit risus, ut pharetra libero turpis eget sem. Pellentesque bibendum lectus libero, ac posuere erat ultricies in. Proin sit amet tempor nunc, id gravida turpis. Duis vitae libero vitae neque fermentum laoreet. In eu magna non enim vulputate lacinia. Aenean fermentum id purus et tincidunt. ', 'Los Angeles, CA', 0);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Funky Chicken Nuggets', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac eros sed velit efficitur eleifend sed in urna. Nullam euismod ex vitae quam elementum, nec efficitur nulla facilisis. Vestibulum convallis metus in justo dignissim, vel tempus eros suscipit. In commodo efficitur ligula, non feugiat justo feugiat sit amet. Suspendisse faucibus ante non vehicula fringilla. Integer lacinia hendrerit nunc, nec elementum nibh vehicula vitae.', 'Chicago, IL', 0);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Groovy Gummy Bears', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce at feugiat nisi, eget tincidunt odio. Maecenas ullamcorper dolor in magna commodo feugiat. In ut tellus vitae justo maximus gravida vel ut dui. In ultricies nisl risus, vitae sodales orci commodo non. Sed ac mi ut felis tempus euismod vel sit amet libero. Curabitur auctor, ligula et ultricies fermentum, mi ex tempus leo, vitae congue enim dolor a ante. Sed eleifend nisi et hendrerit lacinia. Nulla facilisi.', 'Miami, FL', 0);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Wacky Watermelons', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec posuere ante at lorem congue ultrices. Nulla porttitor eleifend ligula, eu tempor justo egestas a. Curabitur id diam erat. Morbi pellentesque, sem ac luctus malesuada, mi lectus fermentum lacus, at tristique arcu ligula at justo. Donec non consectetur lorem. Vestibulum convallis sagittis fermentum. Morbi sed nisi quis nisi feugiat congue eu in dui. Proin blandit quam eget orci tempus, at posuere lorem tristique.', 'Seattle, WA', 0);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Silly Strawberry Jams', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tincidunt velit ut purus sollicitudin, id consequat felis interdum. Ut ut sapien risus. Cras dictum massa vel turpis finibus euismod. Nulla rutrum malesuada fringilla. Nam dictum tempor magna, nec tincidunt urna lobortis quis. Duis iaculis nisl et lectus scelerisque, at molestie orci laoreet. Proin vitae mauris sed lectus cursus dictum. Cras tempor magna eget velit bibendum dictum. Duis in mi quam. ', 'Houston, TX', 0);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Crazy Coconut Crew', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in lacus eu lorem suscipit interdum eu in nibh. Phasellus non enim non tortor eleifend sodales a sit amet risus. Integer viverra est nec enim scelerisque, nec mattis sapien volutpat. In vitae velit nec ex varius aliquet. Curabitur vestibulum lacus felis, eget tristique massa malesuada a. Pellentesque sit amet tempus felis. ', 'Dallas, TX', 1);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Zany Zucchini Zebras', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget est eu libero luctus mattis eu sit amet tortor. Ut ullamcorper tincidunt ipsum at pellentesque. Nulla sed velit vel purus cursus bibendum. Sed ut urna non justo suscipit pretium et ut arcu. Sed varius nibh eu eros dictum, eu malesuada ipsum efficitur. Curabitur facilisis, libero at fermentum vehicula, odio nisi lobortis dolor, sit amet cursus dui nulla in sapien.', 'San Francisco, CA', 1);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Wacky Waffle Wizards', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac elit elit. Integer ut nulla sit amet mi auctor venenatis. Nam eleifend justo eu sem convallis, eget interdum risus tempus. Maecenas commodo est id libero suscipit, ac congue lorem ullamcorper.', 'Denver, CO', 0);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Jumping Jellybeans', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fermentum nec dui ac suscipit. Integer a ligula rutrum, consequat ligula in, efficitur sapien. Nulla sit amet nulla eget nulla eleifend viverra. Vestibulum convallis massa in arcu eleifend aliquam.', 'Austin, TX', 1);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Radical Raspberry Rabbits', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam placerat fermentum lorem, a elementum ipsum rutrum nec. Nullam viverra neque vel sapien tristique, id fermentum libero dignissim. Integer varius tellus mi, non posuere est molestie nec. Nam auctor mi id sollicitudin consequat. Donec nec efficitur magna. Integer vitae ante vestibulum, mattis lorem a, vehicula velit. ', 'Portland, OR', 1);

INSERT INTO SQUADS (SquadPK, SquadName, SquadDesc, SquadLocation, IsDeleted) 
VALUES (NEWID(), 'The Bouncing Banana Bunch', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ullamcorper, nisi a vestibulum congue, metus lorem fermentum justo, in volutpat purus ipsum nec mauris. Pellentesque mattis mi vitae neque sollicitudin iaculis. Nullam sit amet velit arcu. Vivamus dignissim, arcu at pharetra facilisis, felis nunc fringilla justo, id sollicitudin lacus sem non turpis.', 'Phoenix, AZ', 0);


-- Randomly associate Users to Squads.
-- Declare variables to store the number of users and squads
DECLARE @NumUsers INT
DECLARE @NumSquads INT

-- Get the total number of users
SELECT @NumUsers = COUNT(*) FROM USERS

-- Get the total number of squads
SELECT @NumSquads = COUNT(*) FROM SQUADS

-- Insert random squad members
DECLARE @CounterA INT = 1

WHILE @CounterA <= 100 -- Change 100 to the desired number of random squad members
BEGIN
    -- Generate a random UserPK
    DECLARE @RandomUserPK UNIQUEIDENTIFIER
    SELECT TOP 1 @RandomUserPK = UserPK FROM USERS ORDER BY NEWID()

    -- Generate a random SquadPK
    DECLARE @RandomSquadPK UNIQUEIDENTIFIER
    SELECT TOP 1 @RandomSquadPK = SquadPK FROM SQUADS ORDER BY NEWID()

    -- Check if the selected user is already a member of the chosen squad
    IF NOT EXISTS (SELECT 1 FROM SquadMembers WHERE SquadFK = @RandomSquadPK AND UserFK = @RandomUserPK)
    BEGIN
        -- Determine if the user is the squad master
        DECLARE @IsSquadMaster BIT
        IF NOT EXISTS (SELECT 1 FROM SquadMembers WHERE SquadFK = @RandomSquadPK)
            SET @IsSquadMaster = 1
        ELSE
            SET @IsSquadMaster = 0

        -- Generate a random JoinDate between Jan 1, 2022 and Today
        DECLARE @JoinDate DATE
        SET @JoinDate = DATEADD(DAY, -1 * RAND() * DATEDIFF(DAY, '2022-01-01', GETDATE()), GETDATE())

        -- Generate a random value to determine if the record should be deleted
        DECLARE @IsDeleted FLOAT
        SET @IsDeleted = RAND()

        -- Insert the squad member record
        INSERT INTO SquadMembers (SquadMemberPK, SquadFK, UserFK, IsSquadMaster, JoinDate, IsDeleted)
        VALUES (NEWID(), @RandomSquadPK, @RandomUserPK, @IsSquadMaster, @JoinDate, CASE WHEN @IsDeleted < 0.95 THEN 0 ELSE 1 END)
    END

    SET @CounterA = @CounterA + 1
END


-- Declare variables to store the number of days and users
DECLARE @NumDays INT
DECLARE @NumUsersB INT

-- Get the total number of days (Monday - Sunday)
SET @NumDays = 6

-- Get the total number of users
SELECT @NumUsersB = COUNT(*) FROM USERS

-- Insert random availability records for each user
DECLARE @CounterB INT = 1

WHILE @CounterB <= @NumUsersB
BEGIN
    -- Generate a random number of availability records between 6 and 20
    DECLARE @NumRecords INT
    SET @NumRecords = ROUND(RAND() * (20 - 6) + 6, 0)

    -- Get the UserPK for the current user
    DECLARE @CurrentUserPK UNIQUEIDENTIFIER
    SELECT TOP 1 @CurrentUserPK = u.UserPk
		FROM Users u
		LEFT JOIN UserAvailability ua ON u.UserPk = ua.UserFK
		GROUP BY u.UserPk
		HAVING COUNT(ua.AvailabilityPK) = 0

    -- Insert random availability records for the current user
    DECLARE @DayCounter INT = 1

    WHILE @DayCounter <= @NumRecords
    BEGIN
        -- Generate a random DayEnum value between 1 and 7 (representing Monday - Sunday)
        DECLARE @RandomDayEnum INT
        SET @RandomDayEnum = ROUND(RAND() * (@NumDays), 0)

        -- Generate a random StartTime between 00:00 and 23:45 (in 15-minute increments)
        DECLARE @RandomStartTime TIME
        SET @RandomStartTime = DATEADD(MINUTE, ROUND(RAND() * 95, 0) * 15, '00:00')

        -- Generate a random EndTime after the StartTime
        DECLARE @RandomEndTime TIME
        SET @RandomEndTime = DATEADD(MINUTE, ROUND(RAND() * (96 - DATEPART(MINUTE, @RandomStartTime)), 0) * 15, @RandomStartTime)

        -- If EndTime is before StartTime, swap them
        IF @RandomEndTime <= @RandomStartTime
        BEGIN
            DECLARE @Temp TIME
            SET @Temp = @RandomStartTime
            SET @RandomStartTime = @RandomEndTime
            SET @RandomEndTime = @Temp
        END

        -- Generate a random value to determine if the record should be deleted
        DECLARE @IsDeletedB FLOAT
        SET @IsDeletedB = RAND()

        -- Insert the availability record
        INSERT INTO UserAvailability (AvailabilityPK, UserFK, DayEnum, StartTime, EndTime, IsDeleted)
        VALUES (NEWID(), @CurrentUserPK, @RandomDayEnum, @RandomStartTime, @RandomEndTime, CASE WHEN @IsDeletedB < 0.95 THEN 0 ELSE 1 END)

        SET @DayCounter = @DayCounter + 1
    END

    SET @CounterB = @CounterB + 1
END

---- END OF CHATGPT SEED SCRIPT