@startuml Leave Squad
actor user
participant ScheduSquad as app
database Database as db

note over user
Prerequisite:
User is logged in.
User is NOT the
Squadmaster of the
Squad they are leaving.
end note

user -> app : Select Hamburger Icon
app -> db : Request List of User's Squads
db --> app : Return List of User's Squads
app --> user : Display User Squad Menu
alt user selects Squad from User Squad Menu
    user -> app : Select a Squad from the User Squad Menu
    app -> db : Request Selected Squad's Member List and Availabilities
    db --> app : Return Selected Squad's Details
    app --> user : Load Selected Squad's Squad Screen
    user -> app : Select "Leave the Squad" Button
else user leaves Squad from User Squad Menu
    user -> app : Select Cog Icon next to Squad
    app --> user : Displays "Leave Squad" Context Menu
    user -> app : Select "Leave Squad" Option 
end

app -> db : Remove Logged In User from Selected Squad
db --> app : Return Current User's Availability
app --> user : Load Landing Screen

@enduml