@startuml Update Availability
actor user
participant ScheduSquad as app
database Database as db

note over user
Prerequisite: User is
logged in.
end note

user -> app : Select User Icon
app --> user : Open User Menu
user -> app : Select "Update Availability"

loop until user leaves screen
    app -> db : Request Current User Availability
    db --> app : Return Current User Availability
    app --> user : Load User Availability Screen

    alt add new availability
        user -> app : Select "+Add"
        app --> app : Remove "+Add" Button
        app -> user : Display New Availability Line
        user --> app : Select Available Day and Span

        alt cancel
            user -> app : Select "Cancel" Button
            app --> app : Remove New Availability Span
            app --> app : Display "+Add" Button
        else save
            user -> app : Select "Save" Button
            app --> app : Validate New Availability
            alt end before start
                note over user
                Resume flow from
                "Select 'Cancel' Button" above.
                end note
            else valid entry
                app -> db : Add New Availability
            end
        end
    else edit existing availability
        alt edit existing availability
            user -> app : Select Edit Button
            app --> user : Selected Row Accepts New Input
            user -> app : Selects New Availability Span
            alt cancel
                user -> app : Selects "Cancel" Button
                app --> app : Restores User Availability Screen
            else save
                user -> app : Selects "Save" Button
                app --> app: Validates New Availability
                alt end before start
                    note over user
                    Resume flow from
                    "Select 'Cancel' Button" above.
                    end note
                else valid entry
                    app -> db : Edit Selected Availability Span
                end
            end
        else delete availability
            user -> app : Select Delete Button
            app -> db : Delete Logged In User's Selected Availability
        end
    end
end
@enduml